export const SIGN_IN = "SIGN_IN";
export const SIGN_IN_SUCCESS = "SIGN_IN_SUCCESS";
export const SIGN_IN_FAILURE = "SIGN_IN_FAILURE";

export const SIGN_UP = "SIGN_UP";
export const SIGN_UP_SUCCESS = "SIGN_UP_SUCCESS";
export const SIGN_UP_FAILURE = "SIGN_UP_FAILURE";

export const USER_DATA = "USER_DATA";
export const USER_DATA_SUCCESS = "USER_DATA_SUCCESS";
export const USER_DATA_FAILURE = "USER_DATA_FAILURE";

export const EMAIL_ALREADY_TAKEN = "EMAIL_ALREADY_TAKEN";

export const LOG_OUT_USER = "LOG_OUT_USER";
export const SAVE_DATA = "SAVE_DATA";

export const RESEND_EMAIL = "RESEND_EMAIL";
export const RESEND_EMAIL_SUCCESS = "RESEND_EMAIL_SUCCESS";
export const RESEND_EMAIL_FAILURE = "RESEND_EMAIL_FAILURE";

export const VERIFY_TOKEN = "VERIFY_TOKEN";
export const VERIFY_TOKEN_SUCCESS = "VERIFY_TOKEN_SUCCESS";
export const VERIFY_TOKEN_FAILURE = "VERIFY_TOKEN_FAILURE";

export const GET_USER_PROFILE = "GET_USER_PROFILE";
export const GET_USER_PROFILE_SUCCESS = "GET_USER_PROFILE_SUCCESS";
export const GET_USER_PROFILE_FAILURE = "GET_USER_PROFILE_FAILURE";

export const GOOGLE_SIGN_IN = "GOOGLE_SIGN_IN";
export const GOOGLE_SIGN_IN_SUCCESS = "GOOGLE_SIGN_IN_SUCCESS";
export const GOOGLE_SIGN_IN_FAILURE = "GOOGLE_SIGN_IN_FAILURE";

export const FACEBOOK_SIGN_IN = "FACEBOOK_SIGN_IN";
export const FACEBOOK_SIGN_IN_SUCCESS = "FACEBOOK_SIGN_IN_SUCCESS";
export const FACEBOOK_SIGN_IN_FAILURE = "FACEBOOK_SIGN_IN_FAILURE";

export const NOTION_OAUTH_URL = "NOTION_OAUTH_URL";
export const NOTION_OAUTH_URL_SUCCESS = "NOTION_OAUTH_URL_SUCCESS";
export const NOTION_OAUTH_URL_FAILURE = "NOTION_OAUTH_URL_FAILURE";

export const NOTION_OAUTH_TOKEN = "NOTION_OAUTH_TOKEN";
export const NOTION_OAUTH_TOKEN_SUCCESS = "NOTION_OAUTH_TOKEN_SUCCESS";
export const NOTION_OAUTH_TOKEN_FAILURE = "NOTION_OAUTH_TOKEN_FAILURE";

export const GENERATE_PIN_CODE = "GENERATE_PIN_CODE";
export const GENERATE_PIN_CODE_SUCCESS = "GENERATE_PIN_CODE_SUCCESS";
export const GENERATE_PIN_CODE_FAILURE = "GENERATE_PIN_CODE_FAILURE";

export const GENERATE_UNIQUE_URL = "GENERATE_UNIQUE_URL";
export const GENERATE_UNIQUE_URL_SUCCESS = "GENERATE_UNIQUE_URL_SUCCESS";
export const GENERATE_UNIQUE_URL_FAILURE = "GENERATE_UNIQUE_URL_FAILURE";

export const FIND_DATABASE = "FIND_DATABASE";
export const FIND_DATABASE_SUCCESS = "FIND_DATABASE_SUCCESS";
export const FIND_DATABASE_FAILURE = "FIND_DATABASE_FAILURE";

export const FIND_PAGE = "FIND_PAGE";
export const FIND_PAGE_SUCCESS = "FIND_PAGE_SUCCESS";
export const FIND_PAGE_FAILURE = "FIND_PAGE_FAILURE";
